#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, datetime

ENCODING = "utf-8"

################################

#Message Field
SEQN = "sequence num"
DATA = "data"
MSG = "msg"

################################

# Handles receiving/outputting data messages and sending ACKs to the sender
class Receiver:
    def __init__(self):
        """
        Creates a new Receiver
        """

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)  # the connection to the sender
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1] 
        log("Bound to port %d" % self.port)

        self.remote_host = None  
        self.remote_port = None 

        self.packets = [] 
        self.output_num = -1 

    def log(self, message):
      sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + message + "\n")
      sys.stderr.flush()

    def run(self):
        """
        Runs the receiver program, sending ACKs for each data message receiving and outputting data in order
        """

        while True:
            connections = select.select([self.socket], [], [])[0]
            for conn in connections:
                data, addr = conn.recvfrom(65535)

                # Grab the remote host/port if we don't already have it
                if self.remote_host is None:
                    self.remote_host = addr[0]
                    self.remote_port = addr[1]

                # handle the message
                self.recv_msg(data)

    # handles receiving a message from the sender
    def recv_msg(self, data):
        """
        Handles the receipt of a data message from the sender.
        Parameters:
            data (bytes): the message data received
        """

        msg = self.parse_msg(data)
        if msg is None:
            # message was corrupted
            log('Received corrupted message')
        else:
            # message was not corrupted
            log(f"Received data message, idx: {msg[SEQN]}")
            self.send_ack(msg[SEQN])

            if not self.was_received(msg[SEQN]):
                # this is a new packet
                self.insert_packet(msg[DATA], msg[SEQN])
                self.output_data()

    @classmethod
    def parse_msg(cls, data):
        """
        Parses a data message from the sender, ensuring that it hasn't been corrupted.
        Parameters:
            data (bytes): the message data from the sender
        Returns:
            (dict | None): the json object representing the parsed message or None if the message is corrupted
        """

        # parse json
        try:
            msg = json.loads(data.decode(ENCODING))
        except json.decoder.JSONDecodeError:
            return None

        # ensure checksum header is valid
        if MSG not in msg:
            return None

        # ensure ack fields are valid
        fields = [SEQN, DATA]
        for f in fields:
            if f not in msg[MSG]:
                return None

        # verify checksum
        return msg[MSG]

    def send_ack(self, index):
        """
        Sends an ACK message back the sender for a received data message.
        Parameters
            index (int): the index of the data message to acknowledge
        """

        msg = {SEQN: index}
        msg = { MSG: msg}
        log(f'Sending ACK: index={index}')
        self.send(msg)

    def send(self, message):
        """
        Sends a message to the sender
        Parameters:
            message (dict): the json object representing the message to send
        """

        self.socket.sendto(json.dumps(message).encode(ENCODING), (self.remote_host, self.remote_port))

    def output_data(self):
        """
        Outputs any new data in order to STDIN.
        Stops outputting when there is no more data or portion of the data are missing.
        """

        for i in range(self.output_num + 1, len(self.packets)):
            pkt = self.packets[i]
            if self.was_received(i):
                self.output_num = i
                print(pkt, end='', flush=True)
            else:
                # missing data, stop outputting
                return

    def insert_packet(self, pkt, index):
        """
        Inserts a piece of data from a received packet at the correct index in the cache.
        Parameters:
            pkt (str): the data to cache
            index (int): the index of the packet associated with this data
        """

        if index >= len(self.packets):
            self.packets += [None for _ in range(index - len(self.packets))]
            self.packets.append(pkt)
        else:
            self.packets[index] = pkt

    def was_received(self, index):
        """
        Determines whether a packet was received
        Parameters:
            index (int): the index of the packet
        Returns:
            (bool): whether the packet was received (True) or not (False)
        """
        return index < len(self.packets) and self.packets[index] is not None


def log(message):
    """
    print a debug message to STDERR
    Parameters:
        message (Any): the message to log
    """

    sys.stderr.write(str(message) + '\n')
    sys.stderr.flush()


# runs the receiver program
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()